import numpy as np

seed = 12345
def fresh(): return np.random.Generator(np.random.PCG64DXSM(seed))

print("continuous:")
print("standard_normal", list(fresh().standard_normal(5)))
print("standard_gamma", list(fresh().standard_gamma(5.0, 5)))
print("standard_t", list(fresh().standard_t(5.0, 5)))
print("standard_cauchy", list(fresh().standard_cauchy(5)))
print("standard_exponential", list(fresh().standard_exponential(5)))
print("f", list(fresh().f(2.0, 3.0, 5)))
print("chisquare", list(fresh().chisquare(2.0, 5)))
print("beta", list(fresh().beta(2.0, 3.0, 5)))
print("exponential", list(fresh().exponential(2.0, 5)))
print("gamma", list(fresh().gamma(2.0, 3.0, 5)))
print("laplace", list(fresh().laplace(2.0, 3.0, 5)))
print("logistic", list(fresh().logistic(2.0, 3.0, 5)))
print("lognormal", list(fresh().lognormal(0.0, 1.0, 5)))
print("pareto", list(fresh().pareto(2.0, 5)))
print("rayleigh", list(fresh().rayleigh(2.0, 5)))
print("weibull", list(fresh().weibull(2.0, 5)))
print("power", list(fresh().power(2.0, 5)))
print("wald", list(fresh().wald(2.0, 3.0, 5)))
print("vonmises", list(fresh().vonmises(2.0, 3.0, 5)))
print("triangular", list(fresh().triangular(-1.0, 0.0, 1.0, 5)))

print("\nadvanced:")
print("dirichlet", list(fresh().dirichlet([1.0, 2.0, 3.0], 2).flatten()))
print("noncentral_chisquare", list(fresh().noncentral_chisquare(2.0, 3.0, 5)))
print("noncentral_f", list(fresh().noncentral_f(2.0, 3.0, 4.0, 5)))
print("multinomial", list(fresh().multinomial(10, [0.2, 0.3, 0.5], 2).flatten()))

print("\nremaining:")
print("zipf", list(fresh().zipf(2.0, 5)))
print("hypergeometric", list(fresh().hypergeometric(10, 20, 5, 5)))
print("multivariate_hypergeometric", list(fresh().multivariate_hypergeometric([10, 20, 30], 5, 2).flatten()))
